{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    labels:
        app: {{ .Values.appname }}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.hosts.path }}
        backend:
          serviceName: {{ .Release.Name }}-{{ .Values.service.servicename }}
          servicePort: {{ .Values.service.port }}
{{- end }}