apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.servicename }}
  labels:
    app: {{ .Values.appname }}
spec:
  selector:
    app: {{ .Values.appname }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      nodePort: {{ .Values.service.nodeport }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      name: http

      