apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.pvc.claimname }}
  labels:
    app: {{ .Values.appname }}
spec:
  # Using defaukt storage class defined by Minikube
  #storageClassName: "test-sc"
  accessModes:
    - {{ .Values.pvc.accessmodes }}
  resources:
    requests:
      storage: {{ .Values.pvc.request }}